name: Spell checking

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"

jobs:
  build:
    name: Spell checking
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.0.0
      with:
        fetch-depth: 2
    - uses: check-spelling/check-spelling@prerelease
      with:
        config: .github/actions/spelling-data
        experimental_apply_changes_via_bot: 1
        suppress_push_for_open_pull_request: 1
        checkout: true
        spell_check_this: check-spelling/spell-check-this@prerelease
        post_comment: 0

